# See https://docs.redoc.ly/cli/configuration/ for more information.
organization: adobe-developers
extends:
    - minimal
apis:
  Commerce(SaaS0):
    root: /src/openapi/saas-schema.yaml
    labels:
      - main
  Commerce1(SaaS1):
    root: /saas-schema.yaml
    labels:
      - notmain
features.openapi:
  pagination: section
  hideHostname: true
  sortPropsAlphabetically: true
  pathInMiddlePanel: true
  hideDownloadButton: false
  hideTryItPanel: true
  showExtensions: true
  nativeScrollbars: true
  ctrlFHijack: true
  scrollYOffset: .site-nav
  sortTagsAlphabetically: true
  sortOperationsAlphabetically: true