# See https://docs.redoc.ly/cli/configuration/ for more information.

organization: adobe
extends:
    - minimal
apis:
  Commerce(Admin)@2.4.5:
    root: openapi/admin-schema-2.4.5.yaml
    labels:
      - main
  Commerce(Customer)@2.4.5:
    root: openapi/customer-schema-2.4.5.yaml
  Commerce(Guest)@2.4.5:
    root: openapi/guest-schema-2.4.5.yaml
  Commerce(Admin)@2.3.7:
    root: openapi/admin-schema-2.3.7.yaml
  Commerce(Customer)@2.3.7:
    root: openapi/customer-schema-2.3.7.yaml
  Commerce(Guest)@2.3.7:
    root: openapi/guest-schema-2.3.7.yaml
features.openapi:
  pagination: section
  hideHostname: true
  sortPropsAlphabetically: true
  pathInMiddlePanel: true
  hideDownloadButton: false
  hideTryItPanel: true
  showExtensions: true
  nativeScrollbars: true
  ctrlFHijack: true
  htmlTemplate: template/template.hbs
  scrollYOffset: .site-nav
  theme:
    typography:
      fontSize: '16px'
      lineHeight: '1.5em'
      fontWeightRegular: '400'
      fontWeightBold: '600'
      fontWeightLight: '300'
      fontFamily: 'Adobe Clean, sans-serif'
      links:
        color: '#3474DE'
      headings:
        fontFamily: 'Adobe Clean, sans-serif'
        fontWeight: '400'
        lineHeight: '1.6em'
      heading1:
        fontSize: '45px'
        fontWeight: '400'
        color: '#2b2b2c'
      heading2:
        fontSize: '32px'
        fontWeight: '400'
        color: '#2b2b2c'
      code:
        fontSize: '14px'
        backgroundColor: '#080808'
    colors:
      tonalOffset: 0.2
      primary:
        main: '#2b2b2c'
      success:
        light: '#ecf7ed'
      error:
        main: '#cc0000'
      responses:
        success:
          backgroundColor: '#ecf7ed'
        error:
          backgroundColor: '#ffebeb'
    rightPanel:
      backgroundColor: '#1E1E1E'
