---
name: Deploy GitHub Pages preview
on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  preview:
    uses: AdobeDocs/commerce-contributor/.github/workflows/github-pages-preview.yml@ds_COMDOX-1736
    with:
      branch: ${{ github.ref_name }}
