---
###########################
## Pull request testing ##
###########################
name: CI
# Documentation:
# - Workflow: https://help.github.com/en/articles/workflow-syntax-for-github-actions
# - SuperLinter: https://github.com/github/super-linter
# - Markdown linter: https://github.com/DavidAnson/markdownlint
# - Link validation: https://github.com/remarkjs/remark-validate-links

######################################################
# Start the job on a pull request to the main branch #
######################################################
on:
  pull_request:
    branches: [main]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files
          # within `super-linter`
          fetch-depth: 0

      - name: Lint files
        # Use full version number to avoid cases when a next
        # released version is buggy

        # About slim image: https://github.com/github/super-linter#slim-image
        uses: github/super-linter/slim@v4.9.2
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_GITLEAKS: true

          # The Markdown rules are defined at
          # .github/linters/.markdown-lint.yml

          # Documentation on rules:
          # https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md
          VALIDATE_MARKDOWN: true
          VALIDATE_YAML: true
      
      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      - name: Check internal links
        run: npm run test:links

      - name: Build site
        # Run build step only if link check is successful
        if: ${{ success() }}
        run: npm run build